<?php

namespace AppBundle\Repository;

/**
 * AfsprakenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfsprakenRepository extends \Doctrine\ORM\EntityRepository
{
}
