<?php

namespace AppBundle\Repository;

/**
 * DoktersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoktersRepository extends \Doctrine\ORM\EntityRepository
{
}
