<?php

namespace AppBundle\Repository;

/**
 * LokalenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LokalenRepository extends \Doctrine\ORM\EntityRepository
{
}
