<?php

namespace AppBundle\Repository;

/**
 * Product2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product2Repository extends \Doctrine\ORM\EntityRepository
{
}
