app_web:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation

captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
